import React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Social Hub by FarkhanMhd",
  description: "Generated by create next app",
  authors: [{ name: "Farkhan Muhammad", url: "https://github.com/farkhanmhd" }],
};

export default function HomePage() {
  return <h1>Start Here</h1>;
}
